[tools]
rojo = { source = "rojo-rbx/rojo", version = "=7.4.0" }
selene = { source = "Kampfkarren/selene", version = "=0.25.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=0.14.3" }
darklua = { github = "seaofvoices/darklua", version = "=0.13.0" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
run-in-roblox = { github = "rojo-rbx/run-in-roblox", version = "=0.3.0" }
